-- MySQL Script generated by MySQL Workbench
-- Thu Jun 15 11:53:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbP3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydbP3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbP3` DEFAULT CHARACTER SET utf8 ;
USE `mydbP3` ;

-- -----------------------------------------------------
-- Table `mydbP3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`wine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `manufacture_year` VARCHAR(45) NOT NULL,
  `domain` VARCHAR(100) NOT NULL,
  `region` VARCHAR(100) NOT NULL,
  `cepage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_of_tag` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`wine_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`wine_seller` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`seller_has_wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`seller_has_wine` (
  `wine_seller_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  PRIMARY KEY (`wine_seller_id`, `wine_id`),
  INDEX `fk_seller_has_wine_wine1_idx` (`wine_id` ASC) VISIBLE,
  CONSTRAINT `fk_seller_has_wine_wine_seller1`
    FOREIGN KEY (`wine_seller_id`)
    REFERENCES `mydbP3`.`wine_seller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seller_has_wine_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydbP3`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workshop_category` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `price` DECIMAL NOT NULL,
  `max_participants` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`session_has_wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`session_has_wine` (
  `wine_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`wine_id`, `session_id`),
  INDEX `fk_session_has_wine_session1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_has_wine_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydbP3`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_has_wine_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydbP3`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `won_contest` TINYINT NULL,
  `selected_for_context` TINYINT NULL,
  PRIMARY KEY (`id`, `user_id`, `session_id`),
  INDEX `fk_recipe_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_recipe_session1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydbP3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydbP3`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`note` (
  `wine_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `note` INT NOT NULL,
  PRIMARY KEY (`wine_id`, `user_id`, `session_id`),
  INDEX `fk_note_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_note_session1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydbP3`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydbP3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydbP3`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`mix_wine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`mix_wine` (
  `recipe_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  `percent_wine` INT NULL,
  PRIMARY KEY (`recipe_id`, `wine_id`),
  INDEX `fk_mix_wine_wine1_idx` (`wine_id` ASC) VISIBLE,
  CONSTRAINT `fk_mix_wine_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydbP3`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mix_wine_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `mydbP3`.`wine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`user_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`user_has_tag` (
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `comment` TEXT(1000) NULL,
  PRIMARY KEY (`user_id`, `tag_id`),
  INDEX `fk_user_has_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_tag_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydbP3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydbP3`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`session_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`session_has_user` (
  `user_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `session_id`),
  INDEX `fk_user_has_session_session1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_user_has_session_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_session_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydbP3`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_session_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydbP3`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbP3`.`note_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydbP3`.`note_has_tag` (
  `note_wine_id` INT NOT NULL,
  `note_user_id` INT NOT NULL,
  `note_session_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`note_wine_id`, `note_user_id`, `note_session_id`, `tag_id`),
  INDEX `fk_note_has_tag_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_note_has_tag_note1_idx` (`note_wine_id` ASC, `note_user_id` ASC, `note_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_has_tag_note1`
    FOREIGN KEY (`note_wine_id` , `note_user_id` , `note_session_id`)
    REFERENCES `mydbP3`.`note` (`wine_id` , `user_id` , `session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `mydbP3`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
