INSERT INTO
	mydb.wine (
		name,
		color,
		manufacture_year,
		`domain`,
		region,
		appellation,
		cepage,
		image,
		comment
	)
VALUES
	(
		'Blanc de Blanc',
		'Blanc',
		'1979',
		'Ruinart',
		'Champagne',
		'Champagne',
		'Muscat',
		'http://localhost:8080/imgwine/whitebottle.png',
		'Robe pâle reflets verts. Nez franc et typé, de la finesse. Bon équilibre, assez plein, franc et fruité. Finale sapide.'
	),
	(
		'Chablis',
		'Blanc',
		'2021',
		'Domaine de Vauroux',
		'Bourgogne',
		'Petit Chablis',
		'Chardonnay',
		'http://localhost:8080/imgwine/whitebottle2.png',
		'Robe jaune pâle reflets or. Nez ouvert sur des notes de caramel beurre salé, de chocolat blanc, de vanille, pointe de fumé et de pierre à fusil. Attaque ciselée, franche, belle finesse, de la tension, de la fraicheur. Bon équilibre. Caractère sur le pain grillé, les épices, et des notes fumées. Finale sapide, croquante, sur le citron vert et le sel marin.'
	),
	(
		'La fiole du Pape',
		'Rouge',
		'2004',
		'Maison Brotte',
		'Rhône',
		'Côtes du Rhône',
		'Cinsault',
		'http://localhost:8080/imgwine/redbottle.png',
		'Robe grenat aux reflets brique. Nez ouvert et bouqueté de fruits confiturés, confits, de pruneaux cuits, notes animales de fourrure, un boisé fondu assez torréfié. Bon équilibre sur un vin charnu, les tanins sont mûrs, assez ronds et souples. Le caractère prolonge le nez sur un bouquet de fruits confits, de moka et de torréfaction.'
	),
	(
		'Le sang de la vigne',
		'Rouge',
		'1995',
		'Chateau La Louvière',
		'Bordeaux',
		'Pauillac',
		'Pinot noir',
		'http://localhost:8080/imgwine/redbottle2.png',
		'Robe grenat reflets brique sombre et dense. Nez ouvert sur des notes de coulis de mûres, de poivre noir, et de prune confite, pointe mentholée. Attaque pleine, veloutée, charnue, sur gratin de fruits rouges, le cacao, pointe florale. Finale ample, charpentée, à patiner, sur les fruits rouges et les épices. Belle finesse !'
	),
	(
		'Le larmes de la terre',
		'Blanc',
		'1920',
		'Domaine de la Motte',
		'Alsace',
		'Crémant d’Alsace',
		'Pinot blanc',
		'http://localhost:8080/imgwine/whitebottle3.png',
		'Robe pâle reflets vert brillant. Nez franc et ouvert de fleurs blanches, de fenouil, pointe de buis, de laurier sauce. Bel équilibre sur un vin franc, droit avec de la finesse, corps moyen, sec et nerveux. Caractère de fruits frais, de pêches blanches, d''abricots frais, notes de mangue, d''ananas, puis épicé de menthe poivrée, de laurier sauce. Belle allonge sur une pointe de minéralité, sapide.'
	),
	(
		'Château Corbin',
		'Rouge',
		'2016',
		'Château Corbin',
		'Bordeaux',
		'Saint Emilion',
		'Merlot, Cabernet Franc, Cabernet Sauvignon',
		'http://localhost:8080/imgwine/redbottle3.png',
		'Robe brique reflets tuilés sombre, nez de torréfaction, de poivron grillé, de coulis de cassis, de myrtilles, de corne brûlé, équilibré sur une attaque assez ronde et souple, chaleureuse, joli caractère avec des notes animales, de torréfaction, finale souple et fondue avec une pointe de petits fruits rouges.'
	),
	(
		'Château Rahoul',
		'Rouge',
		'2018',
		'Château Rahoul',
		'Bordeaux',
		'Graves',
		'Merlot, Petit Verdot, Cabernet Sauvignon',
		'http://localhost:8080/imgwine/redbottle.png',
		'Robe grenat sombre reflets rouge vif. Nez ouvert sur des notes d''eucalyptus, de café torréfié, de prune rôtie et de muscade, pointe réglisse. Attaque souple, tanins satinés, petit corps, petit caractère sur les épices et le jus de griottes, pointe caramel. Finale sapide, bonne équilibre, petite allonge sur le bois torréfié et la reglisse.'
	),
	(
		'Château Magnol',
		'Rouge',
		'2018',
		'Château Magnol',
		'Bordeaux',
		'Haut Medoc',
		'Merlot, Cabernet Franc, Petit Verdot, Cabernet Sauvignon',
		'http://localhost:8080/imgwine/redbottle2.png',
		'Robe grenat aux reflets brique. Nez ouvert et bouqueté de fruits confiturés, confits, de pruneaux cuits, notes animales de fourrure, un boisé fondu assez torréfié. Bon équilibre sur un vin charnu, les tanins sont mûrs, assez ronds et souples. Le caractère prolonge le nez sur un bouquet de fruits confits, de moka et de torréfaction.'
	),
	(
		'Duc de Belmont',
		'Rouge',
		'2020',
		'Jean Loron',
		'Bourgogne',
		'Bourgogne',
		'Gamay',
		'http://localhost:8080/imgwine/redbottle3.png',
		'Robe pourpre sombre. Joli nez franc de fruits noirs, de bigarreaux, pointe de genièvre. Bon équilibre, de la finesse, corsé avec une pointe chaleureuse; Caractère qui prolonge les notes du nez avec de la réglisse. Belle finale vineuse et charnue sur la longueur.'
	),
	(
		'Côte de Beaune Village',
		'Rouge',
		'2018',
		'Côte de Beaune Village',
		'Bourgogne',
		'Côte de Beaune Village',
		'Pinot Noir',
		'http://localhost:8080/imgwine/redbottle.png',
		'Robe tuilée reflets brique limpide. Nez ouvert et bouqueté de sirop de cerises, de caramel blond, de bois vanillé, notes épicées de genièvre. Bon équilibre sur un vin corsé, petite enveloppe. Caractère qui prolonge les arômes du nez avec des notes de vieux cuir, pointe de fumée, tanins fondus. Finale franche, prêt à consommer.'
	),
	(
		'Chiroubles les 3 puits',
		'Rouge',
		'2020',
		'Jacques Charlet',
		'Beaujolais',
		'Chiroubles',
		'Gamay',
		'http://localhost:8080/imgwine/redbottle2.png',
		'Robe pourpre reflets violines, limpide et brillante. Nez ouvert sur des notes de cerise, de myrtille et de chocolat noir, pointe anisée. Attaque souple, croquante, de la fraicheur, du fruit, tanins veloutés, bon équilibre. Finale sapide, corsée, racée, sur les fruits des bois, pointe de thym, belle allonge satinée et fruitée.'
	),
	(
		'Côte Brouilly les Esnards',
		'Rouge',
		'2020',
		'Jean Loron',
		'Beaujolais',
		'Côte de Brouilly',
		'Gamay',
		'http://localhost:8080/imgwine/redbottle3.png',
		'Robe pourpre sombre, joli nez franc de lilas, de cassis, pointe de buis, de réglisse, bel équilibre, franc, corsé et plein, caractère qui pointe sur les fruits mûrs, les épices douces, tanins mûrs assez serrés, encore un peu jeunes, finale longue et tendue.'
	),
	(
		'Berticot cuvée Première',
		'Blanc',
		'2022',
		'Berticot',
		'Sud-Ouest',
		'Côtes de Duras',
		'Sauvignon',
		'http://localhost:8080/imgwine/whitebottle.png',
		'Robe pâle aux reflets encore verts lumineuse. Nez frais, franc de fruits blancs, de fruits frais, notes de fenouil frais, de cassis. Bon équilibre sur un vin franc, droit, pointe chaleureuse mais joli caractère frais, de la finesse. Bonne finale assez croquante.'
	),
	(
		'A Casetta Corse',
		'Blanc',
		'2021',
		'A Casetta Corse',
		'Méditerranée',
		'Vin De Corse',
		'Vermentinu',
		'http://localhost:8080/imgwine/whitebottle.png',
		'Robe pâle reflets argentés voilée. Nez à ouvrir franc et frais sur une pointe de minéralité puis des arômes de fleurs blanches, de poivre blanc, une pointe de laurier sauce. Bon équilibre sur un corps assez léger et rond. Finale sapide.'
	),
	(
		'Jurançon sec Cami Salie',
		'Blanc',
		'2020',
		'Lionel Osmin & Cie',
		'Sud-Ouest',
		'Jurançon Sec',
		'Gros Manseng, Petit manseng',
		'http://localhost:8080/imgwine/whitebottle2.png',
		'Robe pâle quelques reflets verts. Joli nez à ouvrir de fleurs blanches, de fruits blancs, d''abricots frais. Bel équilibre sur un corps assez léger, gourmand, de la fraicheur. Bonne sucrosité, joli fruit qui prolonge les arômes du nez, notes de grains de muscats frais et croquants. Bulles fondues, belle allonge gourmande, croquante et fraiche.'
	),
	(
		'Petites récoltes coteaux Peyriac',
		'Blanc',
		'2022',
		'Les petites récoltes',
		'Languedoc-Roussillon',
		'IGP Côteaux De Peyriac',
		'Chardonnay, Marsanne',
		'http://localhost:8080/imgwine/whitebottle3.png',
		'Robe de couleur jaune clair, reflet vert. Nez franc, sur les fruits à chair blanche notes vanillée, les fruits exotiques. Attaque souple de l''enveloppe, de la tension, de l''équilibre. Allonge franche. Caractère sur les agrumes, de la tension, du corps sans lourdeur. Bonne persistance.'
	),
	(
		'Château La Noë',
		'Blanc',
		'2022',
		'Château La Noë',
		'Loire et Centre',
		'Muscadet',
		'Melon de Bourgogne',
		'http://localhost:8080/imgwine/whitebottle.png',
		'Robe pâle aux reflets verts. Nez franc et droit, frais de fleurs blanches, de zestes d''agrumes, notes de pomélos, pointe iodée minérale. Bon équilibre sur un vin franc, droit au corps assez léger, perlant, de la finesse. Caractère assez signé. Bonne allonge sapide avec une pointe de minéralité.'
	),
	(
		'Château Haut Rian',
		'Blanc',
		'2021',
		'Château Haut Rian',
		'Bordeaux',
		'Entre Deux Mers',
		'Sauvignon blanc, Sémillon',
		'http://localhost:8080/imgwine/whitebottle2.png',
		'Robe paille pâle reflets vert pâle, limpide et brillante. Nez ouvert sur des notes de buis, de citron vert et de bourgeon de cassis, pointe iodée. Attaque souple, sur la fraicheur, de la tension, de la minéralité, corps moyen. Finale sapide, sur le bourgeon de cassis et les coquilles d''huitres, belle finesse.'
	),
	(
		'La fleur de Couhins',
		'Blanc',
		'2020',
		'Château Couhins',
		'Bordeaux',
		'Pessac Léognan',
		'Sauvignon',
		'http://localhost:8080/imgwine/whitebottle3.png',
		'Robe jaune pâle quelques reflets encore verts. Joli nez franc, frais et ouvert de mimosas, de bourgeon de cassis, notes de zestes d''agrumes, de pomélos, bon équilibre sur un corps moyen, franc, de la finesse, sec et nerveux. Joli caractère avec des notes de coquilles d''huitres, de minéralité et de zestes de citron. Belle allonge franche et signée un peu chaleureuse.'
	),
	(
		'Château Bouscaut Blanc',
		'Blanc',
		'2018',
		'Château Bouscaut',
		'Bordeaux',
		'Pessac Léognan',
		'Sauvignon, Sémillon',
		'http://localhost:8080/imgwine/whitebottle.png',
		'Robe jaune paille pâle brillante, joli nez franc et ouvert de fruits exotiques, de fruits blancs, notes vanillées, pointe mentholée, bon équilibre sur un vin corsé, charpenté, avec un joli caractère de fruits exotiques, de fleurs blanches, notes de pain beurré, finale avec une pointe minérale.'
	),
	(
		'Château Olivier',
		'Rouge',
		'2013',
		'Château Olivier',
		'Bordeaux',
		'Pessac Léognan',
		'Merlot, Petit Verdot, Cabernet Sauvignon',
		'http://localhost:8080/imgwine/redbottle.png',
		'Robe brique reflets tuilé sombre. Nez de bois brulé, de fumée, notes de réglisse, corsé, petit caractère de fruits confits, de notes grillées, tanins sans gras, finale franche.'
	);

INSERT INTO mydb.`user` (firstname,lastname,email, password, role) VALUES
	 ('Celia','Golden','ceci.brams@gmail.com','$argon2id$v=19$m=65536,t=3,p=4$oKINUTSPrDaQKKNBnI3xuA$wz0ebKYpLsWWWYOUuw58jmrXKl7lMmlJGYHhNqZTJMM','ROLE_USER'),
	 ('Saverio','Platinium','save.cutolo@gmail.com','$argon2id$v=19$m=65536,t=3,p=4$0kcgVUGnvv+FiSkqoWY1fg$3h3mUp4tjJJJmgPL57vjHIlN7wAOJcihSyjHHp4eICg','ROLE_USER'),
	 ('JM','Guirlande','millet.jm@live.com','$argon2id$v=19$m=65536,t=3,p=4$jFoy3cUueXp0P/8huFOoVw$dN6Zk+sfhZTEPwiB8BiSx4OTAwVYEQ7jYhnfyw95xlU','ROLE_USER'),
	 ('Tom','Nana','lelaurain.tom@gmail.com','$argon2id$v=19$m=65536,t=3,p=4$t67zhRKcXGLqJ3p9KO5f5Q$q4RFIN4d02J76sr6HWh/bXmIjryzO6M7qLvLyxkANn8','ROLE_USER'),
	 ('Thomas','Te','lonjon.thomas@gmail.com','$argon2id$v=19$m=65536,t=3,p=4$8iGCr2Bkx5pnsMzSkG3o8w$elbVXhunIGEVS8XewsCy/SvFce7zDxxbq14fLkMZpo0','ROLE_USER');

INSERT INTO
	mydb.`session` (
		category,
		`date`,
		price,
		max_participants,
		location_id
	)
VALUES
	('Dégustation', '2023-08-01 16:00:00', 40, 10, 3),
	('Dégustation', '2023-08-03 16:00:00', 40, 10, 5),
	('Dégustation', '2023-08-05 14:00:00', 40, 10, 5),
	('Dégustation', '2023-08-17 16:00:00', 40, 10, 5),
	('Dégustation', '2023-08-19 16:00:00', 40, 10, 7),
	('Dégustation', '2023-08-21 20:00:00', 40, 10, 8),
	('Dégustation', '2023-08-23 20:00:00', 40, 10, 9),
	('Dégustation', '2023-08-25 20:00:00', 40, 10, 5),
	('Dégustation', '2023-08-27 16:00:00', 40, 10, 9),
	('Dégustation', '2023-08-29 20:00:00', 40, 10, 3),
	('Dégustation', '2023-08-31 16:00:00', 40, 10, 7),
	('Dégustation', '2023-09-01 20:00:00', 40, 10, 2),
	('Dégustation', '2023-09-03 16:00:00', 40, 10, 5),
	('Dégustation', '2023-09-05 20:00:00', 40, 10, 4),
	('Dégustation', '2023-09-07 16:00:00', 40, 10, 3),
	('Dégustation', '2023-09-09 20:00:00', 40, 10, 2),
	('Dégustation', '2023-09-11 16:00:00', 40, 10, 1),
	('Dégustation', '2023-09-13 20:00:00', 40, 10, 1),
	('Dégustation', '2023-09-17 20:00:00', 40, 10, 3),
	('Dégustation', '2023-09-19 16:00:00', 40, 10, 1),
	('Création', '2023-08-02 20:00:00', 70, 10, 2),
	('Création', '2023-08-04 16:00:00', 70, 10, 2),
	('Création', '2023-08-06 16:00:00', 70, 10, 2),
	('Création', '2023-08-08 16:00:00', 70, 10, 4),
	('Création', '2023-08-10 20:00:00', 70, 10, 10),
	('Création', '2023-08-12 14:00:00', 70, 10, 6),
	('Création', '2023-08-14 16:00:00', 70, 10, 7),
	('Création', '2023-08-16 20:00:00', 70, 10, 8),
	('Création', '2023-08-18 20:00:00', 70, 10, 9),
	('Création', '2023-08-20 17:00:00', 70, 10, 10),
	('Création', '2023-08-22 16:00:00', 70, 10, 9),
	('Création', '2023-08-24 20:00:00', 70, 10, 8),
	('Création', '2023-08-26 14:00:00', 70, 10, 10),
	('Création', '2023-08-28 14:00:00', 70, 10, 6),
	('Création', '2023-08-30 16:00:00', 70, 10, 6),
	('Création', '2023-09-02 20:00:00', 70, 10, 4),
	('Création', '2023-09-04 16:00:00', 70, 10, 3),
	('Création', '2023-09-06 20:00:00', 70, 10, 2),
	('Création', '2023-09-08 20:00:00', 70, 10, 6),
	('Création', '2023-09-10 20:00:00', 70, 10, 2);

INSERT INTO mydb.location (place_name,lat,lng,image) VALUES
	 ('La Cascade du Déroc',44.6462,3.07042,'http://localhost:8080/workshops/deroc.jpeg'),
	 ('La Tour d''Apcher',44.8167,3.32193,'http://localhost:8080/workshops/TourApcher.jpeg'),
	 ('Le Château de la Baume',44.6496,3.19343,'http://localhost:8080/workshops/ChateauBaume.jpeg'),
	 ('Sainte-Enimie',44.3647,3.4144,'http://localhost:8080/workshops/Sainte_enimie.jpeg'),
	 ('Le Dolmen de Changefège',44.497,3.44417,'http://localhost:8080/workshops/Dolmen_Changefege.jpeg'),
	 ('La Cathédrale Notre-Dame de Mende',44.5173,3.49796,'http://localhost:8080/workshops/ND_Mende.jpg'),
	 ('La Ferme Caussenarde',44.218,3.32417,'http://localhost:8080/workshops/ferme_caussenarde.jpg'),
	 ('La Garde Guérin',44.4776,3.9347,'http://localhost:8080/workshops/garde_guerin.jpeg'),
	 ('La Cascade de Runes',44.3793,3.6746,'http://localhost:8080/workshops/cascade_runes.jpeg'),
	 ('Le Mont Lozère',44.4257,3.73904,'http://localhost:8080/workshops/mont_lozere.jpeg');

INSERT INTO
	mydb.session_has_user (user_id, session_id)
VALUES
	(1, 1),
	(2, 1),
	(5, 1),
	(3, 2),
	(4, 2);

INSERT INTO
	mydb.session_has_wine (wine_id, session_id)
VALUES
	(1, 1),
	(2, 1),
	(3, 1),
	(4, 1),
	(1, 2),
	(2, 2),
	(3, 2),
	(4, 2),
	(5, 1),
	(5, 2);

INSERT INTO mydb.tag (type_of_tag,category,sub_category,name) VALUES
     ('User','Couleur',NULL,'Vin Rouge'),
     ('User','Couleur',NULL,'Virn Blanc'),
     ('User','Arôme',NULL,'Fruité'),
     ('User','Arôme',NULL,'Floral'),
     ('User','Arôme',NULL,'Végétal'),
     ('User','Arôme',NULL,'Boisé'),
     ('User','Arôme',NULL,'Balsamique'),
     ('User','Arôme',NULL,'Minéral'),
     ('User','Arôme',NULL,'Animal'),
     ('User','Arôme',NULL,'Epicé'),
     ('User','Sucrosité',NULL,'Sec'),
     ('User','Sucrosité',NULL,'Moelleux'),
     ('Wine','Oeil','Couleur','Framboise'),
     ('Wine','Oeil','Couleur','Cerise'),
     ('Wine','Oeil','Couleur','Rubis'),
     ('Wine','Oeil','Couleur','Pourpre'),
     ('Wine','Oeil','Couleur','Violet'),
     ('Wine','Oeil','Couleur','Grenart'),
     ('Wine','Oeil','Couleur','Tuilé'),
     ('Wine','Oeil','Couleur','Jaune vert'),
     ('Wine','Oeil','Couleur','Jaune paille'),
     ('Wine','Oeil','Couleur','Or vert'),
     ('Wine','Oeil','Couleur','Or jaune '),
     ('Wine','Oeil','Couleur','Doré'),
     ('Wine','Oeil','Couleur','Ambré'),
     ('Wine','Oeil','Couleur','Roux'),
     ('Wine','Oeil','Intensité de la Couleur ','Pâle'),
     ('Wine','Oeil','Intensité de la Couleur ','Claire'),
     ('Wine','Oeil','Intensité de la Couleur ','Soutenue'),
     ('Wine','Oeil','Intensité de la Couleur ','Intense'),
     ('Wine','Oeil','Fluidité des Larmes','Visqueuses'),
     ('Wine','Oeil','Fluidité des Larmes','Épaisses'),
     ('Wine','Oeil','Fluidité des Larmes','Coulantes'),
     ('Wine','Oeil','Fluidité des Larmes','Fluides'),
     ('Wine','Oeil','Limpidité','Trouble'),
     ('Wine','Oeil','Limpidité','Floue'),
     ('Wine','Oeil','Limpidité','Voilée'),
     ('Wine','Oeil','Limpidité','Limpide'),
     ('Wine','Oeil','Brillance','Terne'),
     ('Wine','Oeil','Brillance','Lumineuse'),
     ('Wine','Oeil','Brillance','Étincelante'),
     ('Wine','Nez','Intensité des Arômes','Fermé'),
     ('Wine','Nez','Intensité des Arômes','Discret'),
     ('Wine','Nez','Intensité des Arômes','Aromatique'),
     ('Wine','Nez','Intensité des Arômes','Ouvert'),
     ('Wine','Nez','Complexité','Douteux'),
     ('Wine','Nez','Complexité','Ouvert'),
     ('Wine','Nez','Complexité','Franc'),
     ('Wine','Nez','Complexité','Complexe'),
     ('Wine','Nez','Familles Arômatiques','Fruité'),
     ('Wine','Nez','Familles Arômatiques','Floral'),
     ('Wine','Nez','Familles Arômatiques','Végétal'),
     ('Wine','Nez','Familles Arômatiques','Boisé'),
     ('Wine','Nez','Familles Arômatiques','Balsamique'),
     ('Wine','Nez','Familles Arômatiques','Minéral'),
     ('Wine','Nez','Familles Arômatiques','Animal'),
     ('Wine','Nez','Familles Arômatiques','Epicé'),
     ('Wine','La Bouche','Tanins','Apre'),
     ('Wine','La Bouche','Tanins','Charpenté'),
     ('Wine','La Bouche','Tanins','Fondu'),
     ('Wine','La Bouche','Tanins','Lisse'),
     ('Wine','La Bouche','Acidité','Moux'),
     ('Wine','La Bouche','Acidité','Frais'),
     ('Wine','La Bouche','Acidité','Vif'),
     ('Wine','La Bouche','Acidité','Nerveux'),
     ('Wine','La Bouche','Robe','Légère'),
     ('Wine','La Bouche','Robe','Fluide'),
     ('Wine','La Bouche','Robe','Charpentée'),
     ('Wine','La Bouche','Robe','Epaisse'),
     ('Wine','La Bouche','Sucre','Sec'),
     ('Wine','La Bouche','Sucre','Doux'),
     ('Wine','La Bouche','Sucre','Moelleux'),
     ('Wine','La Bouche','Sucre','Liquoreux'),
     ('Wine','La Bouche','Alcool','Faible'),
     ('Wine','La Bouche','Alcool','Généreux'),
     ('Wine','La Bouche','Alcool','Gras'),
     ('Wine','La Bouche','Alcool','Alcooleux'),
     ('Wine','La Bouche','Persistance Arômatique','Courte'),
     ('Wine','La Bouche','Persistance Arômatique','Développée'),
     ('Wine','La Bouche','Persistance Arômatique','Longue'),
     ('Wine','La Bouche','Persistance Arômatique','Persistante'),
     ('Wine','La Bouche','Familles Arômatiques','Fruité'),
     ('Wine','La Bouche','Familles Arômatiques','Végétal'),
     ('Wine','La Bouche','Familles Arômatiques','Boisé'),
     ('Wine','La Bouche','Familles Arômatiques','Minéral'),
     ('Wine','La Bouche','Familles Arômatiques','Animal'),
     ('Wine','La Bouche','Familles Arômatiques','Epicé'),
     ('Wine','La Bouche','Familles Arômatiques','Floral'),
     ('Wine','La Bouche','Familles Arômatiques','Balsamique');

INSERT INTO
	mydb.user_has_tag (user_id, tag_id)
VALUES

INSERT INTO
	mydb.user_has_favorite (user_id, wine_id)
VALUES
	(1, 1),
	(2, 1),
	(3, 1),
	(5, 1),
	(1, 2),
	(3, 2),
	(4, 2),
	(5, 2),
	(1, 3),
	(3, 3),
	(4, 3),
	(5, 3),
	(2, 4),
	(4, 4),
	(5, 4),
	(2, 5),
	(3, 5),
	(5, 5);

INSERT INTO
	mydb.recipe (
		user_id,
		session_id,
		won_contest,
		selected_for_context
	)
VALUES
	(1, 2, 0, 1),
	(2, 2, 1, 1),
	(4, 2, 0, 1);

INSERT INTO
	mydb.mix_wine (recipe_id, wine_id, percent_wine)
VALUES
	(1, 1, 70),
	(1, 2, 15),
	(1, 3, 15),
	(2, 1, 10),
	(2, 4, 70),
	(2, 5, 20),
	(3, 1, 70),
	(3, 2, 15),
	(3, 3, 15);

INSERT INTO
	mydb.note (wine_id, user_id, session_id, note)
VALUES
	(1, 1, 2, 10),
	(2, 1, 2, 9),
	(3, 1, 2, 8),
	(4, 1, 2, 5),
	(5, 1, 2, 7),
	(1, 2, 2, 5),
	(2, 2, 2, 1),
	(3, 2, 2, 3),
	(4, 2, 2, 10),
	(5, 2, 2, 4);
INSERT INTO mydb.session_has_wine (wine_id,session_id) VALUES
	 (1,1),
	 (2,1),
	 (3,1),
	 (4,1),
	 (1,2),
	 (2,2),
	 (3,2),
	 (4,2),
     (5,1),
     (5,2);


INSERT INTO mydb.tag (type_of_tag,category,sub_category,name) VALUES
	 ('User','Couleur',NULL,'Vin Rouge'),
	 ('User','Couleur',NULL,'Vin Blanc'),
	 ('User','Arôme',NULL,'Fruité'),
	 ('User','Arôme',NULL,'Floral'),
	 ('User','Arôme',NULL,'Végétal'),
	 ('User','Arôme',NULL,'Boisé'),
	 ('User','Arôme',NULL,'Balsamique'),
	 ('User','Arôme',NULL,'Minéral'),
	 ('User','Arôme',NULL,'Animal'),
	 ('User','Arôme',NULL,'Epicé'),
	 ('User','Sucrosité',NULL,'Sec'),
	 ('User','Sucrosité',NULL,'Moelleux'),
	 ('Wine','Oeil','Couleur','Framboise'),
	 ('Wine','Oeil','Couleur','Cerise'),
	 ('Wine','Oeil','Couleur','Rubis'),
	 ('Wine','Oeil','Couleur','Pourpre'),
	 ('Wine','Oeil','Couleur','Violet'),
	 ('Wine','Oeil','Couleur','Grenart'),
	 ('Wine','Oeil','Couleur','Tuilé'),
	 ('Wine','Oeil','Couleur','Jaune vert'),
	 ('Wine','Oeil','Couleur','Jaune paille'),
	 ('Wine','Oeil','Couleur','Or vert'),
	 ('Wine','Oeil','Couleur','Or jaune '),
	 ('Wine','Oeil','Couleur','Doré'),
	 ('Wine','Oeil','Couleur','Ambré'),
	 ('Wine','Oeil','Couleur','Roux'),
	 ('Wine','Oeil','Intensité de la Couleur ','Pâle'),
	 ('Wine','Oeil','Intensité de la Couleur ','Claire'),
	 ('Wine','Oeil','Intensité de la Couleur ','Soutenue'),
	 ('Wine','Oeil','Intensité de la Couleur ','Intense'),
	 ('Wine','Oeil','Fluidité des Larmes','Visqueuses'),
	 ('Wine','Oeil','Fluidité des Larmes','Épaisses'),
	 ('Wine','Oeil','Fluidité des Larmes','Coulantes'),
	 ('Wine','Oeil','Fluidité des Larmes','Fluides'),
	 ('Wine','Oeil','Limpidité','Trouble'),
	 ('Wine','Oeil','Limpidité','Floue'),
	 ('Wine','Oeil','Limpidité','Voilée'),
	 ('Wine','Oeil','Limpidité','Limpide'),
	 ('Wine','Oeil','Brillance','Terne'),
	 ('Wine','Oeil','Brillance','Lumineuse'),
	 ('Wine','Oeil','Brillance','Étincelante'),
	 ('Wine','Nez','Intensité des Arômes','Fermé'),
	 ('Wine','Nez','Intensité des Arômes','Discret'),
	 ('Wine','Nez','Intensité des Arômes','Aromatique'),
	 ('Wine','Nez','Intensité des Arômes','Ouvert'),
	 ('Wine','Nez','Complexité','Douteux'),
	 ('Wine','Nez','Complexité','Ouvert'),
	 ('Wine','Nez','Complexité','Franc'),
	 ('Wine','Nez','Complexité','Complexe'),
	 ('Wine','Nez','Familles Arômatiques','Fruité'),
	 ('Wine','Nez','Familles Arômatiques','Floral'),
	 ('Wine','Nez','Familles Arômatiques','Végétal'),
	 ('Wine','Nez','Familles Arômatiques','Boisé'),
	 ('Wine','Nez','Familles Arômatiques','Balsamique'),
	 ('Wine','Nez','Familles Arômatiques','Minéral'),
	 ('Wine','Nez','Familles Arômatiques','Animal'),
	 ('Wine','Nez','Familles Arômatiques','Epicé'),
	 ('Wine','La Bouche','Tanins','Apre'),
	 ('Wine','La Bouche','Tanins','Charpenté'),
	 ('Wine','La Bouche','Tanins','Fondu'),
	 ('Wine','La Bouche','Tanins','Lisse'),
	 ('Wine','La Bouche','Acidité','Moux'),
	 ('Wine','La Bouche','Acidité','Frais'),
	 ('Wine','La Bouche','Acidité','Vif'),
	 ('Wine','La Bouche','Acidité','Nerveux'),
	 ('Wine','La Bouche','Robe','Légère'),
	 ('Wine','La Bouche','Robe','Fluide'),
	 ('Wine','La Bouche','Robe','Charpentée'),
	 ('Wine','La Bouche','Robe','Epaisse'),
	 ('Wine','La Bouche','Sucre','Sec'),
	 ('Wine','La Bouche','Sucre','Doux'),
	 ('Wine','La Bouche','Sucre','Moelleux'),
	 ('Wine','La Bouche','Sucre','Liquoreux'),
	 ('Wine','La Bouche','Alcool','Faible'),
	 ('Wine','La Bouche','Alcool','Généreux'),
	 ('Wine','La Bouche','Alcool','Gras'),
	 ('Wine','La Bouche','Alcool','Alcooleux'),
	 ('Wine','La Bouche','Persistance Arômatique','Courte'),
	 ('Wine','La Bouche','Persistance Arômatique','Développée'),
	 ('Wine','La Bouche','Persistance Arômatique','Longue'),
	 ('Wine','La Bouche','Persistance Arômatique','Persistante'),
	 ('Wine','La Bouche','Familles Arômatiques','Fruité'),
	 ('Wine','La Bouche','Familles Arômatiques','Végétal'),
	 ('Wine','La Bouche','Familles Arômatiques','Boisé'),
	 ('Wine','La Bouche','Familles Arômatiques','Minéral'),
	 ('Wine','La Bouche','Familles Arômatiques','Animal'),
	 ('Wine','La Bouche','Familles Arômatiques','Epicé'),
	 ('Wine','La Bouche','Familles Arômatiques','Floral'),
	 ('Wine','La Bouche','Familles Arômatiques','Balsamique');


INSERT INTO mydb.user_has_tag (user_id,tag_id) VALUES
	 (1,1),
	 (4,1),
	 (1,2),
	 (3,3),
	 (1,4),
	 (2,4),
	 (5,4),
	 (5,5),
	 (2,6),
	 (3,6),
	 (4,7),
	 (5,7),
	 (3,8),
	 (4,8),
	 (2,9);

INSERT INTO mydb.user_has_favorite (user_id,wine_id) VALUES
	 (1,1),
	 (2,1),
	 (3,1),
	 (5,1),
	 (1,2),
	 (3,2),
	 (4,2),
	 (5,2),
	 (1,3),
	 (3,3),
	 (4,3),
	 (5,3),
	 (2,4),
	 (4,4),
	 (5,4),
	 (2,5),
	 (3,5),
	 (5,5);

INSERT INTO mydb.recipe (user_id,session_id,won_contest,selected_for_context) VALUES
	 (1,2,0,1),
	 (2,2,1,1);


INSERT INTO mydb.mix_wine (recipe_id,wine_id,percent_wine) VALUES
	 (1,1,70),
	 (1,2,15),
	 (1,3,15),
	 (2,1,10),
	 (2,4,70),
	 (2,5,20);


INSERT INTO mydb.note (wine_id,user_id,session_id,note) VALUES
	 (1,1,2,10),
	 (2,1,2,9),
	 (3,1,2,8),
	 (4,1,2,5),
	 (5,1,2,7),
	 (1,2,2,5),
	 (2,2,2,1),
	 (3,2,2,3),
	 (4,2,2,10),
	 (5,2,2,4);


INSERT INTO mydb.note_has_tag (note_id,tag_id) VALUES
	 (1,10),
	 (10,10),
	 (1,11),
	 (9,11),
	 (10,11),
	 (2,12),
	 (9,12),
	 (2,13),
	 (8,13),
	 (3,14),
	 (8,14),
	 (3,15),
	 (7,15),
	 (4,16),
	 (7,16),
	 (4,17),
	 (6,17),
	 (5,18),
	 (6,18),
	 (5,19);

INSERT INTO
	mydb.note_has_tag (note_id, tag_id)
VALUES
	(1, 10),
	(10, 10),
	(1, 11),
	(9, 11),
	(10, 11),
	(2, 12),
	(9, 12),
	(2, 13),
	(8, 13),
	(3, 14),
	(8, 14),
	(3, 15),
	(7, 15),
	(4, 16),
	(7, 16),
	(4, 17),
	(6, 17),
	(5, 18),
	(6, 18),
	(5, 19);